import React from "react";

const Course_MCA_DataScience = [
 {
  coursecode: "MC460101",
  coursetitle: "Mathematics for Data Science",
  l: 3,
  t: 1,
  p: 0,
  credits: 4,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC460102",
  coursetitle: "Introduction to Programming & Problem Solving",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC460103",
  coursetitle: "Computing with Python",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC460104",
  coursetitle: "Technical Communication",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC460105",
  coursetitle: "Introduction to Informatics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC460106",
  coursetitle: "EAA-II Swachha Bharat Mission (SBM)",
  l: 0,
  t: 0,
  p: 2,
  credits: 1,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC460201",
  coursetitle: "Data Communication and Networks",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC460202",
  coursetitle: "Data Structures",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC460203",
  coursetitle: "Database Management Systems",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC460204",
  coursetitle: "Object Oriented Programming using Java",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC460205",
  coursetitle: "Discrete Mathematics & Graph Theory",
  l: 3,
  t: 1,
  p: 0,
  credits: 4,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC460206",
  coursetitle: "EAA-I Sports/Innovative Project/NCC/NSS",
  l: 0,
  t: 0,
  p: 2,
  credits: 1,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC460301",
  coursetitle: "Artificial Intelligence",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "MC460302",
  coursetitle: "Operating Systems",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "MC460303",
  coursetitle: "Machine Learning",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "MC460304",
  coursetitle: "Design and Analysis of Algorithms",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "MC460305",
  coursetitle: "Data Preparation & Visualization",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "MC460401",
  coursetitle: "Big Data Analytics",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC460402",
  coursetitle: "Bioinformatics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC460403",
  coursetitle: "Deep Learning",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC460404",
  coursetitle: "Information Retrieval",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC460405",
  coursetitle: "Computer Vision",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC460406",
  coursetitle: "Seminar & Presentation",
  l: 0,
  t: 0,
  p: 2,
  credits: 1,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC460501",
  coursetitle: "Human Computer Interaction",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "MC460502",
  coursetitle: "Minor Project I",
  l: 0,
  t: 0,
  p: 22,
  credits: 11,
  dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "MC4605XX",
  coursetitle: "Elective – I/MOOC",
  l: 0,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "MC4605XX",
  coursetitle: "Elective – II/MOOC",
  l: 0,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "MC460601",
  coursetitle: "Major Project/Internship",
  l: 0,
  t: 0,
  p: 40,
  credits: 20,
  dept: "CSE",
  sem_elect: 6,
 },
 {
  coursecode: "MC46XX10",
  coursetitle: "Generative Deep Model",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX11",
  coursetitle: "Explainable AI",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX12",
  coursetitle: "Internet of Things",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX13",
  coursetitle: "Game Theory",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX14",
  coursetitle: "Augmented Reality/Virtual Reality",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX15",
  coursetitle: "Intrusion Detection",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX16",
  coursetitle: "Malware Analysis",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX17",
  coursetitle: "Digital Forensic",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX18",
  coursetitle: "Text Analytics",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX20",
  coursetitle: "Reinforcement Learning",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX21",
  coursetitle: "Blockchain Technology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX22",
  coursetitle: "Data Mining and Warehousing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX23",
  coursetitle: "Recommendation Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX24",
  coursetitle: "Cloud Computing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX25",
  coursetitle: "Computer System and Security",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX26",
  coursetitle: "Biomedical Engineering",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX27",
  coursetitle: "Soft Computing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX28",
  coursetitle: "Distributed and Parallel Computing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX29",
  coursetitle: "Federated Learning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX30",
  coursetitle: "Quantum Computing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX31",
  coursetitle: "Pattern Recognition",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX32",
  coursetitle: "Nature-Inspired Computing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX33",
  coursetitle: "Optimization Techniques",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX34",
  coursetitle: "Health Informatics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC46XX35",
  coursetitle: "Image Processing Techniques",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
];

export default Course_MCA_DataScience;
