import React from "react";

const Course_MCA_ArtificialIntelligence = [
 {
  coursecode: "MC470101",
  coursetitle: "Problem Solving through C",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC470102",
  coursetitle: "Mathematical Foundations of Computer Applications",
  l: 3,
  t: 1,
  p: 0,
  credits: 4,
   dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC470103",
  coursetitle: "Computer Networks",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC470104",
  coursetitle: "Technical Communication",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC470105",
  coursetitle: "Computer Organization and Architecture",
  l: 3,
  t: 1,
  p: 0,
  credits: 4,
   dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC470106",
  coursetitle: "EAA -II Swachha Bharat Mission (SBM)",
  l: 0,
  t: 0,
  p: 2,
  credits: 1,
   dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MC470201",
  coursetitle: "Data Structures",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC470202",
  coursetitle: "Computing with Python",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC470203",
  coursetitle: "Database Management Systems",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC470204",
  coursetitle: "Operating Systems",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC470205",
  coursetitle: "Ad-hoc & Sensor Networks",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC470206",
  coursetitle: "EAA - I Sports/Innovative Project/NCC/NSS",
  l: 0,
  t: 0,
  p: 2,
  credits: 1,
   dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MC470301",
  coursetitle: "Design and Analysis of Algorithms",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "MC470302",
  coursetitle: "Artificial Intelligence",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "MC470303",
  coursetitle: "Object Oriented Programming using JAVA",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "MC470304",
  coursetitle: "Internet of Things",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "MC470305",
  coursetitle: "Machine Learning",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "MC470401",
  coursetitle: "Deep Learning",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC470402",
  coursetitle: "Artificial Intelligence of Things",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC470403",
  coursetitle: "Data Visualization",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC470404",
  coursetitle: "Web Programming",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC470405",
  coursetitle: "Natural Language Processing",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
   dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC470406",
  coursetitle: "Mobile Applications Development",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC470407",
  coursetitle: "Seminar & Presentation",
  l: 0,
  t: 0,
  p: 2,
  credits: 1,
   dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "MC470501",
  coursetitle: "Information Security",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "MC470502",
  coursetitle: "Minor Project",
  l: 0,
  t: 0,
  p: 22,
  credits: 11,
   dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "MC4705XX",
  coursetitle: "Elective-I/MOOC",
  l: 0,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "MC4705XX",
  coursetitle: "Elective-II/MOOC",
  l: 0,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "MCXX0601",
  coursetitle: "Project / Industrial Training",
  l: 0,
  t: 0,
  p: 40,
  credits: 20,
   dept: "CSE",
  sem_elect: 6,
 },
 {
  coursecode: "MC47XX10",
  coursetitle: "Generative Deep Models",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX11",
  coursetitle: "Explainable AI",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX12",
  coursetitle: "Information Retrieval",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX13",
  coursetitle: "Game Theory",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX14",
  coursetitle: "Augmented Reality (AR) and Virtual Reality (VR)",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX15",
  coursetitle: "Intrusion Detection",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX16",
  coursetitle: "Malware Analysis",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX17",
  coursetitle: "Digital Forensic",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX18",
  coursetitle: "Text Analytics",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX19",
  coursetitle: "Computer Vision",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX20",
  coursetitle: "Reinforcement Learning",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX21",
  coursetitle: "Blockchain Technology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX22",
  coursetitle: "Data Mining and Warehousing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX23",
  coursetitle: "Recommendation Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX24",
  coursetitle: "Cloud Computing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX25",
  coursetitle: "Image Processing Techniques",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX26",
  coursetitle: "Computer System and Security",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX27",
  coursetitle: "Smart Agriculture",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX28",
  coursetitle: "Human Computer Interaction",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "MC47XX29",
  coursetitle: "Social IoT",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
   dept: "CSE",
  sem_elect: "EL",
 },
];

export default Course_MCA_ArtificialIntelligence;
